#!/bin/bash
# called from in the scripts directory:
#  - prior to  building
#  - in  starting a slurm job to run the model
#  - interactive analyses post-model run,  to have consistent envoronment (and include ncview)
# Also enables the setup to be captured in one file to hold (some of the) provenance of tests.

# Convention being used:
# a case corresponds to a specific build of a model (defined compiler options, opt file, code...)
# a run uses that build
# In testing there will be many runs for one case to explore SLURM options
# such as number of nodes.

# the script create_case copies tjhis and sets it up

module load PrgEnv-cray 
module load cray-hdf5-parallel
module load cray-netcdf-hdf5parallel


# module load nco/4.9.6-gcc-10.1.0
# module load ncview/ncview-2.1.7-gcc-10.1.0  


export MITGCM_ROOTDIR=/work/n02/shared/mjmn02/PAS/MITgcm

# account - this is for the ecse... replace by  your project one.

export HECACC=ecseab06-guest

export MITGCM_OPT=../scripts/dev_linux_amd64_cray_archer2
