function WriteNetcdfOutput()

dimensions.name={'nPointGL','nTime','ny','nx'};
dimensions.dim=[inf;endmonth-startmonth+1;80;800];
variables.name={'time','iceVolume','iceVAF','groundedArea','xGL','yGL',...
   'iceThicknessGL','uBaseGL','vBaseGL','uSurfaceGL','vSurfaceGL','uMeanGL','vMeanGL',...
   'x','y','iceThickness','upperSurface','lowerSurface','basalMassBalance',...
   'groundedMask','floatingMask','basalTractionMagnitude','uBase','vBase','uSurface','vSurface',...
   'uMean','vMean'};
variables.dim=[0,1,0,0; 0,1,0,0; 0,1,0,0; 0,1,0,0; 1,1,0,0; 1,1,0,0; ...
    1,1,0,0; 1,1,0,0; 1,1,0,0; 1,1,0,0; 1,1,0,0; 1,1,0,0; 1,1,0,0; ...
    0,0,0,1; 0,0,1,0; 0,1,1,1; 0,1,1,1; 0,1,1,1; 0,1,1,1; ...
    0,1,1,1; 0,1,1,1; 0,1,1,1; 0,1,1,1; 0,1,1,1; 0,1,1,1; 0,1,1,1; ...
    0,1,1,1; 0,1,1,1];
variables.units={'s','m^3','m^3','m^2','m','m',...
    'm','m/s','m/s','m/s','m/s','m/s','m/s',...
    'm','m','m','m','m','m/s',...
    'unitless','unitless','Pa','m/s','m/s','m/s','m/s',...
    'm/s','m/s'};
variables.description={'time since start of simulation','total ice volume','volume of ice above flotation','total area of grounded ice',...
    'x coordinates of points on the grounding line','y coordinates of points on the grounding line',...
    'ice thickness at the grounding line','x component of basal velocity at the grounding line',...
    'y component of basal velocity at the grounding line','x component of surface velocity at the grounding line',...
    'y component of surface velocity at the grounding line','x component of mean velocity at the grounding line',...
    'y component of mean velocity at the grounding line','x location of cell centers','y location of cell centers','ice thickness',...
    'upper surface elevation','lower surface elevation','basal mass balance of ice (not water equivalent), positive for melting',...
    'area fraction of grounded ice in a given cell','area fraction of floating ice in a given cell','the magnitude of the tangential basal traction field',...
    'x-component of the basal velocity','y-component of the basal velocity','x-component of the surface velocity','y-component of the surface velocity',...
    'x-component of the vertical mean of the velocity','y-component of the vertical mean of the velocity'};

% generate nc file with variables and dimensions
ncfilename = ['/media/wchm8/JDeRydt-1/Documents/Projects/MISOMIP1/NetCDF_output/',exp,'_COM_ice_UaMITgcm.nc'];

for ii=1:length(variables.name)
    I = find(variables.dim(ii,:)); 
    dim = {dimensions.name{I(1)},dimensions.dim(I(1))};
    for jj=2:length(I)
        dim = {dim{:}, dimensions.name{I(jj)},dimensions.dim(I(jj))};
    end
    nccreate(ncfilename,variables.name{ii},...
         'Dimensions', dim,'FillValue', NaN,...
         'Format','netcdf4','Datatype','single');
    ncwriteatt(ncfilename,variables.name{ii},'units',variables.units{ii});
    ncwriteatt(ncfilename,variables.name{ii},'description',variables.description{ii});
end
ncwriteatt(ncfilename,'/','_FillValue',NaN);