#!/bin/bash

FC=ftn
CC=cc
CPP='/usr/bin/cpp  -traditional-cpp -P'

MPI='true'
DEFINES='-DALLOW_USE_MPI -DALWAYS_USE_MPI -DWORDLENGTH=4'

LIBS='-L${CRAY_MPICH2_DIR}/lib -L${HDF5_DIR}/lib -L$NETCDF_DIR/lib  -lnetcdf -lnetcdff  -lhdf5 -lhdf5_hl'

INCLUDES='-I${CRAY_MPICH2_DIR}/include -I${HDF5_DIR}/include -I${NETCDF_DIR}/include -I${HDF5_INCLUDE_OPTS}'

FFLAGS='-h byteswapio -assume byterecl -convert big_endian -fpe0 -g -traceback'
